import { useEffect, useRef, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import AnalysisMessage from './components/AnalysisMessage';
import { agentTurn, clearSession } from './store/detectionSlice';
import './App.css';

const SAMPLE_TEXT = `Artificial intelligence has transformed the way we create and consume content. While these tools offer incredible efficiency, understanding whether text was written by a person or generated by AI is becoming increasingly important.

Educators, publishers, and professionals who value authenticity need clearer signals than a single score. Breaking a document into sections helps reviewers see where risk concentrates.

This sample includes multiple paragraphs so the agent can target AI-sounding sections and rewrite them to sound more natural.`;

const WELCOME = {
  id: 'welcome',
  role: 'assistant',
  content:
    'Paste text you want to sound less AI-generated. I’ll score each sentence, flag those at or above your threshold, then on your go humanize the flagged spans and return the draft with before/after scores.',
};

function createId() {
  return crypto.randomUUID();
}

function App() {
  const dispatch = useDispatch();
  const [messages, setMessages] = useState([WELCOME]);
  const [text, setText] = useState('');
  const [flagThresholdPercent, setFlagThresholdPercent] = useState(60);
  const { status, sessionId, pending } = useSelector((state) => state.detection);
  const isBusy = status === 'loading';
  const awaitingConfirm = Boolean(pending) && !isBusy;
  const threadRef = useRef(null);

  useEffect(() => {
    const el = threadRef.current;
    if (!el) return;
    el.scrollTop = el.scrollHeight;
  }, [messages, isBusy, pending]);

  const appendAssistantTurn = (payload, { error } = {}) => {
    if (error) {
      setMessages((prev) => [
        ...prev,
        {
          id: createId(),
          role: 'assistant',
          error,
          confirmOptions: [],
        },
      ]);
      return;
    }

    const analysis = payload?.analysis;
    const partial = payload?.partial;
    const confirmOptions =
      payload?.status === 'awaiting_confirmation'
        ? payload.confirmOptions ?? []
        : [];

    if (payload?.status === 'awaiting_confirmation' && partial) {
      setMessages((prev) => [
        ...prev,
        {
          id: createId(),
          role: 'assistant',
          content: 'Sentence-level scores:',
          view: 'sentences',
          partial: {
            ...partial,
            aiScore: null,
            humanScore: null,
            rewrittenAiScore: null,
            rewrittenText: null,
            originalText: null,
          },
          confirmOptions: [],
        },
        {
          id: createId(),
          role: 'assistant',
          content: payload.message,
          view: 'overall',
          partial: {
            ...partial,
            sections: [],
            rewrittenText: null,
            originalText: null,
          },
          confirmOptions,
        },
      ]);
      return;
    }

    const shouldSplitDraft =
      payload?.status === 'completed' &&
      analysis &&
      (analysis.sections?.length > 0 || analysis.rewrittenText);

    if (shouldSplitDraft) {
      setMessages((prev) => [
        ...prev,
        {
          id: createId(),
          role: 'assistant',
          content: 'Sentence-level scores:',
          view: 'sentences',
          analysis: {
            ...analysis,
            rewrittenText: null,
            originalText: null,
            report: null,
            caveats: [],
          },
          confirmOptions: [],
        },
        {
          id: createId(),
          role: 'assistant',
          content: payload.message,
          view: 'draft',
          analysis: {
            ...analysis,
            sections: [],
          },
          confirmOptions: [],
        },
      ]);
      return;
    }

    setMessages((prev) => [
      ...prev,
      {
        id: createId(),
        role: 'assistant',
        content: payload?.message,
        partial: payload?.partial,
        analysis: payload?.analysis,
        view: 'all',
        confirmOptions,
      },
    ]);
  };

  const runTurn = async ({ action, content, userLabel }) => {
    if (isBusy) return;

    if (userLabel) {
      setMessages((prev) => [
        ...prev,
        { id: createId(), role: 'user', content: userLabel },
      ]);
    }

    try {
      const payload = await dispatch(
        agentTurn({
          action,
          sessionId,
          text: content,
          flagThresholdPercent,
        }),
      ).unwrap();
      appendAssistantTurn(payload);
      return payload;
    } catch (err) {
      appendAssistantTurn(null, {
        error:
          typeof err === 'string'
            ? err
            : 'Agent request failed. Is the API running?',
      });
      return null;
    }
  };

  const startAnalysis = async (content) => {
    const trimmed = content.trim();
    if (!trimmed || isBusy) return;
    if (awaitingConfirm) return;

    setText('');
    setMessages((prev) => [
      ...prev,
      { id: createId(), role: 'user', content: trimmed },
    ]);

    if (sessionId) {
      try {
        await dispatch(
          agentTurn({
            action: 'cancel',
            sessionId,
            flagThresholdPercent,
          }),
        ).unwrap();
      } catch {
        // Previous session may already be gone.
      }
      dispatch(clearSession());
    }

    try {
      const payload = await dispatch(
        agentTurn({
          action: 'start',
          sessionId: null,
          text: trimmed,
          flagThresholdPercent,
        }),
      ).unwrap();
      appendAssistantTurn(payload);
    } catch (err) {
      appendAssistantTurn(null, {
        error:
          typeof err === 'string'
            ? err
            : 'Agent request failed. Is the API running?',
      });
    }
  };

  const handleConfirm = () =>
    runTurn({ action: 'confirm', userLabel: 'Continue' });

  const handleSkip = () =>
    runTurn({ action: 'skip', userLabel: 'Skip rewrite' });

  const handleCancel = () =>
    runTurn({ action: 'cancel', userLabel: 'Cancel' });

  const handleSubmit = (event) => {
    event.preventDefault();
    startAnalysis(text);
  };

  const handleKeyDown = (event) => {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      startAnalysis(text);
    }
  };

  const latestConfirmId = [...messages]
    .reverse()
    .find((m) => m.role === 'assistant' && m.confirmOptions?.length > 0)?.id;

  return (
    <div className="app">
      <header className="header">
        <div className="header-copy">
          <h1>Less AI</h1>
          <p className="subtitle">
            Step-by-step humanizer — sentence-level AI detection, then rewrite
            only the flagged spans.
          </p>
        </div>
      </header>

      <main className="chat-shell">
        <div className="chat-thread" ref={threadRef} aria-live="polite">
          {messages.map((message) => (
            <div
              key={message.id}
              className={`chat-row chat-row-${message.role}`}
            >
              <div className={`chat-bubble chat-bubble-${message.role}`}>
                {message.role === 'user' && (
                  <p className="chat-user-text">{message.content}</p>
                )}
                {message.role === 'assistant' && message.content && (
                  <p className="chat-assistant-text">{message.content}</p>
                )}
                {message.role === 'assistant' &&
                  (message.analysis || message.partial || message.error) && (
                    <AnalysisMessage
                      analysis={message.analysis}
                      partial={message.partial}
                      error={message.error}
                      view={message.view ?? 'all'}
                    />
                  )}
                {message.role === 'assistant' &&
                  message.id === latestConfirmId &&
                  awaitingConfirm &&
                  message.confirmOptions?.length > 0 && (
                    <div className="confirm-actions">
                      {message.confirmOptions.includes('confirm') && (
                        <button
                          type="button"
                          className="btn btn-primary"
                          onClick={handleConfirm}
                          disabled={isBusy}
                        >
                          Continue
                        </button>
                      )}
                      {message.confirmOptions.includes('skip') && (
                        <button
                          type="button"
                          className="btn btn-secondary"
                          onClick={handleSkip}
                          disabled={isBusy}
                        >
                          Skip rewrite
                        </button>
                      )}
                      {message.confirmOptions.includes('cancel') && (
                        <button
                          type="button"
                          className="btn btn-secondary"
                          onClick={handleCancel}
                          disabled={isBusy}
                        >
                          Cancel
                        </button>
                      )}
                    </div>
                  )}
              </div>
            </div>
          ))}

          {isBusy && (
            <div className="chat-row chat-row-assistant">
              <div className="chat-bubble chat-bubble-assistant chat-typing">
                <span />
                <span />
                <span />
              </div>
            </div>
          )}
        </div>

        <form className="chat-composer" onSubmit={handleSubmit}>
          <label className="option-row threshold-row">
            <span>Flag threshold</span>
            <input
              type="number"
              min={0}
              max={100}
              step={1}
              value={flagThresholdPercent}
              onChange={(e) => {
                const next = Number(e.target.value);
                if (Number.isNaN(next)) return;
                setFlagThresholdPercent(Math.min(100, Math.max(0, next)));
              }}
              disabled={awaitingConfirm || isBusy}
              aria-label="AI flag threshold percent"
            />
            <span>%</span>
          </label>

          <div className="composer-box">
            <textarea
              className="composer-input"
              placeholder={
                awaitingConfirm
                  ? 'Confirm or cancel the current step above…'
                  : 'Paste text to humanize… (Enter to send, Shift+Enter for newline)'
              }
              value={text}
              onChange={(e) => setText(e.target.value)}
              onKeyDown={handleKeyDown}
              rows={3}
              disabled={isBusy || awaitingConfirm}
            />
            <div className="composer-actions">
              <button
                type="button"
                className="link-btn"
                onClick={() => startAnalysis(SAMPLE_TEXT)}
                disabled={isBusy || awaitingConfirm}
              >
                Try sample
              </button>
              <button
                type="submit"
                className="btn btn-primary"
                disabled={!text.trim() || isBusy || awaitingConfirm}
              >
                {isBusy ? 'Working…' : 'Send'}
              </button>
            </div>
          </div>
        </form>
      </main>
    </div>
  );
}

export default App;
