import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import Gauge from './components/Gauge';
import { clearResult, scanText } from './store/detectionSlice';
import './App.css';

const SAMPLE_TEXT = `Artificial intelligence has transformed the way we create and consume content. While these tools offer incredible efficiency, understanding whether text was written by a person or generated by AI is becoming increasingly important.

Educators, publishers, and professionals who value authenticity need clearer signals than a single score. Breaking a document into sections helps reviewers see where risk concentrates.

This sample includes multiple paragraphs so the integrity-style analysis can show per-section estimates alongside the overall result.`;

function App() {
  const dispatch = useDispatch();
  const [text, setText] = useState('');
  const { result, status, error } = useSelector((state) => state.detection);
  const isScanning = status === 'loading';

  const handleScan = () => {
    if (!text.trim()) return;
    dispatch(scanText(text));
  };

  return (
    <div className="app">
      <header className="header">
        <h1>AI Detector</h1>
        <p className="subtitle">
          Sectioned screening report for human review — not a verdict.
        </p>
      </header>

      <main className="detector-card">
        <section className="input-panel">
          <textarea
            className="text-input"
            placeholder="Type or paste your text."
            value={text}
            onChange={(e) => setText(e.target.value)}
          />

          <div className="input-actions">
            <div className="input-actions-left">
              <button
                className="btn btn-primary"
                onClick={handleScan}
                disabled={!text.trim() || isScanning}
              >
                {isScanning ? 'Analyzing…' : 'Analyze text'}
              </button>
            </div>
            <button
              className="link-btn"
              onClick={() => {
                setText(SAMPLE_TEXT);
                dispatch(clearResult());
              }}
            >
              Try sample text
            </button>
          </div>
        </section>

        <section className="results-panel">
          <div className="results-header">
            <span>Integrity-style analysis</span>
          </div>

          <div className="results-score">
            <h2>
              {result ? `${result.aiScore}%` : '—%'} of this text appears to be
              AI-generated
            </h2>
          </div>

          <Gauge value={result?.aiScore ?? null} />

          <ul className="results-breakdown">
            <li>
              <span className="dot dot-ai" />
              <span>Resembles AI text</span>
              <span className="breakdown-value">
                {result ? `${result.aiScore}%` : '—%'}
              </span>
            </li>
            <li>
              <span className="dot dot-human" />
              <span>No AI text patterns found</span>
              <span className="breakdown-value">
                {result ? `${result.humanScore}%` : '—%'}
              </span>
            </li>
          </ul>

          {error && <p className="results-error">{error}</p>}

          {result?.report && (
            <div className="report-block">
              <h3>Report</h3>
              <p>{result.report}</p>
            </div>
          )}

          {result?.sections?.length > 0 && (
            <div className="sections-block">
              <h3>Sections</h3>
              <ul className="section-list">
                {result.sections.map((section) => (
                  <li key={section.id}>
                    <div className="section-meta">
                      <span className="section-id">#{section.id}</span>
                      <span className="section-score">{section.aiScore}%</span>
                    </div>
                    <p className="section-excerpt">{section.excerpt}</p>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {result?.actionsTaken?.length > 0 && (
            <div className="actions-block">
              <h3>Actions taken</h3>
              <p className="actions-trace">{result.actionsTaken.join(' → ')}</p>
            </div>
          )}

          {result?.caveats?.length > 0 && (
            <ul className="caveats-list">
              {result.caveats.map((caveat) => (
                <li key={caveat}>{caveat}</li>
              ))}
            </ul>
          )}
        </section>
      </main>
    </div>
  );
}

export default App;
