import { useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import Gauge from './components/Gauge';
import { clearResult, scanText } from './store/detectionSlice';
import './App.css';

const SAMPLE_TEXT = `Artificial intelligence has transformed the way we create and consume content. While these tools offer incredible efficiency, understanding whether text was written by a person or generated by AI is becoming increasingly important for educators, publishers, and professionals who value authenticity in their work.`;

function App() {
  const dispatch = useDispatch();
  const [text, setText] = useState('');
  const { result, status } = useSelector((state) => state.detection);
  const isScanning = status === 'loading';

  const handleScan = () => {
    if (!text.trim()) return;
    dispatch(scanText(text));
  };

  return (
    <div className="app">
      <header className="header">
        <h1>AI Detector</h1>
      </header>

      <main className="detector-card">
        <section className="input-panel">
          <textarea
            className="text-input"
            placeholder="Type or paste your text."
            value={text}
            onChange={(e) => setText(e.target.value)}
          />

          <div className="input-actions">
            <div className="input-actions-left">
              <button
                className="btn btn-primary"
                onClick={handleScan}
                disabled={!text.trim() || isScanning}
              >
                {isScanning ? 'Scanning…' : 'Scan for AI'}
              </button>
            </div>
            <button
              className="link-btn"
              onClick={() => {
                setText(SAMPLE_TEXT);
                dispatch(clearResult());
              }}
            >
              Try sample text
            </button>
          </div>
        </section>

        <section className="results-panel">
          <div className="results-header">
            <span>AI Detection results</span>
          </div>

          <div className="results-score">
            <h2>
              {result ? `${result.aiScore}%` : '—%'} of this text appears to be
              AI-generated
            </h2>
          </div>

          <Gauge value={result?.aiScore ?? null} />

          <ul className="results-breakdown">
            <li>
              <span className="dot dot-ai" />
              <span>Resembles AI text</span>
              <span className="breakdown-value">
                {result ? `${result.aiScore}%` : '—%'}
              </span>
            </li>
            <li>
              <span className="dot dot-human" />
              <span>No AI text patterns found</span>
              <span className="breakdown-value">
                {result ? `${result.humanScore}%` : '—%'}
              </span>
            </li>
          </ul>
        </section>
      </main>
    </div>
  );
}

export default App;
